- name: To check dsmadmc
  hosts: ansible-lab
  gather_facts: no
  ignore_errors: true
  become: true
  tasks:
    - name: Add content to file1.txt
      lineinfile:
        path: tsmcred
        line: "{{ lookup('env', 'tsm_app_user') }}"
        create: yes
        mode: 0600

    - name: Add content to file1.txt
      lineinfile:
        path: tsmcred
        line: "{{ lookup('env', 'tsm_app_password') }}"
        create: yes

    - name: To connect to TSM using dsmadmc
      dsmadmccred:
        se: server1
        command: "select * from db"
        dataonly: true
        cred: tsmcred
      register: db

    - name: TO print DB
      debug:
        msg: "{{ db }}"
