- name: To check dsmadmc
  hosts: ansible-lab
  gather_facts: no
  ignore_errors: true
  become: true
  tasks:
    - name: Add ID  to cred file
      lineinfile:
        path: "{{ lookup('env', 'tsm_app_cred') }}"
        line: "{{ lookup('env', 'tsm_app_user') }}"
        create: yes
        mode: 0600

    - name: Add Password to cred file
      lineinfile:
        path: "{{ lookup('env', 'tsm_app_cred') }}"
        line: "{{ lookup('env', 'tsm_app_password') }}"
        create: yes

    - name: To connect to TSM using dsmadmc
      dsmadmccred:
        se: server1
        command: "select * from db"
        dataonly: true
        cred: "{{ lookup('env', 'tsm_app_cred') }}"
      register: db

    - name: TO print DB
      debug:
        msg: "{{ db }}"

    - name: To remove the the cred file at end of the play
      file:
        path: "{{ lookup('env', 'tsm_app_cred') }}"
        state: absent
