- name: To check dsmadmc
  hosts: all
  gather_facts: no
  ignore_errors: true
  tasks:
    - name: Add ID  to cred file
      lineinfile:
        path: .tsmcred
        line: "{{ lookup('env', 'tsm_app_user') }}"
        create: yes
        mode: 0600

    - name: Add Password to cred file
      lineinfile:
        path: .tsmcred
        line: "{{ lookup('env', 'tsm_app_password') }}"
        create: yes

    - name: To connect to TSM using dsmadmc
      dsmadmccred:
        se: "{{ lookup('env', 'tsm_server_node') }}"
        command: "select * from db"
        dataonly: true
        cred: .tsmcred
      register: db

    - name: TO print DB
      debug:
        msg: "{{ db }}"

    - name: To remove the the cred file at end of the play
      file:
        path: .tsmcred
        state: absent
