- name: To check dsmadmc
  hosts: ansible-lab
  gather_facts: no
  ignore_errors: true
  become: true
  vars:
    content1: in04385v
    content2: passwordpassword
  tasks:
    - name: Add content to file1.txt
      lineinfile:
        path: tsmcred
        line: "{{ content1 }}"
        create: yes
        mode: 0600

    - name: Add content to file1.txt
      lineinfile:
        path: tsmcred
        line: "{{ content2 }} "
        create: yes

    - name: To connect to TSM using dsmadmc
      shell: "dsmadmc dataonly=yes -credentialsfile=tsmcred q db"
      register: db

    - name: TO print DB
      debug:
        msg: "{{ db }}"
